version: '3.5'

services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TBOT_SECRET_KEY='youwillneverguess'
      - TBOT_ADMIN_PASSWORD='qwerty'
      - TBOT_ADMIN_USERNAME='admin'
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - flask_data:/var/lib/adserver/data

volumes:
    flask_data: